// generated by Fast Light User Interface Designer (fluid) version 1.00

#include "SketchWindow.h"
#include <FL/Fl.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Window.H>

class SketchUI {
public:
  Fl_Window* makeWindow();
  Fl_Window *winMain;
  SketchWindow *winSketch;
  Fl_Slider *sldSegments;
private:
  inline void cb_sldSegments_i(Fl_Slider*, void*);
  static void cb_sldSegments(Fl_Slider*, void*);
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  Fl_Value_Output *inpSegments;
};
