// generated by Fast Light User Interface Designer (fluid) version 1.00

#include "sketchui.h"

inline void SketchUI::cb_sldSegments_i(Fl_Slider*, void*) {
  inpSegments->value(1 << ((int)sldSegments->value()));
}
void SketchUI::cb_sldSegments(Fl_Slider* o, void* v) {
  ((SketchUI*)(o->parent()->parent()->user_data()))->cb_sldSegments_i(o,v);
}

inline void SketchUI::cb_Close_i(Fl_Button*, void*) {
  winMain->hide();
}
void SketchUI::cb_Close(Fl_Button* o, void* v) {
  ((SketchUI*)(o->parent()->parent()->user_data()))->cb_Close_i(o,v);
}

Fl_Window* SketchUI::makeWindow() {
  Fl_Window* w;
  { Fl_Window* o = winMain = w = new Fl_Window(518, 482, "Sketch!");
    o->user_data((void*)(this));
    { SketchWindow* o = winSketch = new SketchWindow(5, 5, 510, 390);
      o->box(FL_EMBOSSED_FRAME);
    }
    { Fl_Group* o = new Fl_Group(5, 400, 505, 80);
      o->selection_color(51);
      { Fl_Slider* o = sldSegments = new Fl_Slider(385, 420, 120, 20);
        o->type(1);
        o->minimum(2);
        o->maximum(10);
        o->step(1);
        o->value(4);
        o->callback((Fl_Callback*)cb_sldSegments);
        o->align(1);
      }
      { Fl_Button* o = new Fl_Button(220, 450, 80, 25, "Close");
        o->callback((Fl_Callback*)cb_Close);
      }
      { Fl_Value_Output* o = inpSegments = new Fl_Value_Output(330, 420, 50, 20, "Number of Segments:");
        o->maximum(0);
        o->value(16);
        o->textsize(12);
        o->align(5);
      }
      o->end();
    }
    o->end();
  }
  return w;
}
