// generated by Fast Light User Interface Designer (fluid) version 1.00

#include "ui.h"

Fl_Window* UserInterface::makeWindow() {
  Fl_Window* w;
  { Fl_Window* o = winControl = new Fl_Window(214, 224, "This is a window");
    w = o;
    o->user_data((void*)(this));
    o->end();
  }
  return w;
}
