// generated by Fast Light User Interface Designer (fluid) version 1.00

#ifndef ui_h
#define ui_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>

class UserInterface {
public:
  Fl_Window* makeWindow();
  Fl_Window *winControl;
};
#endif
